# Generated by Django 5.0 on 2024-02-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nest', '0002_remove_orders_customer_remove_orders_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
